name: Publish and Release

on:
  push:
    branches: [ "master" ] # Triggers on push to master

jobs:
  build-and-publish:
    runs-on: windows-latest # Required for win-x64 builds
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Update to your .NET version

    - name: Publish App
      run: |
        dotnet publish -c Release -r win-x64 \
          --self-contained true \
          -p:PublishSingleFile=true \
          -p:IncludeAllContentForSelfExtract=true \
          -p:DebugType=None # Exclude PDB files

    - name: Zip Artifacts
      run: |
        $publishDir = "bin/Release/net8.0/win-x64/publish" # Update .NET version if needed
        Compress-Archive -Path "$publishDir/*" -DestinationPath "b_chronicles-win-x64.zip" -Force

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          b_chronicles-win-x64.zip
        tag_name: v${{ github.ref_name }} # Uses branch name/tag
        name: Release v${{ github.ref_name }}
        body: "Automated release for ${{ github.sha }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Auto-generated secret